services:
  animalml:
    build: .
    runtime: nvidia
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - FLASK_ENV=development
    stdin_open: true
    tty: true